### ISSUE TITLE
NFR: Add in the MCAE tracking code to Mack Trucks CA 

### ISSUE THREAD

**Issue by mollyaljenkins** [aemsites/vg-macktrucks-com#21]
### Description 
The Mack Trucks Salesforce team needs to be able to see what pages the leads/contacts have visited, to do so two IDs need to be configured on the constant file. 

**User AC:**
- [ ] The user continues to see the cookie pop up which allows the customer to determine if they want to accept all cookies or select specific cookies for their browsing experience

**Editor AC:**
- [ ] The content editor (mainly CMS team) can add, edit, or remove the code when the need arises.

**Non-functional AC:**
- [ ] The code is generated from Salesforce and not another non-Volvo approved, non-north star compliant code source

MT CA Code
<script type="text/javascript">
piAId = '1039343';
piCId = '158869';
piHostname = '[pi.pardot.com](http://pi.pardot.com/)';
(function() {
  function async_load(){
    var s = document.createElement('script'); s.type = 'text/javascript';
    s.src = ('https:' == document.location.protocol ? 'https://pi/' : 'http://cdn/') + '.[pardot.com/pd.js](http://pardot.com/pd.js)';
    var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
  }
  if(window.attachEvent) { window.attachEvent('onload', async_load); }
  else { window.addEventListener('load', async_load, false); }
})();
</script>
