### ISSUE TITLE
Template: Bulldog Magazine Article

### ISSUE THREAD

**Issue by shirin27** [aemsites/vg-macktrucks-com#88]
From vg-macktrucks-com-rd created by [Gonzalo-CG](https://github.com/Gonzalo-CG): Netcentric/vg-macktrucks-com-rd#132  

### Business Value
As a content author, I want a quick way to create new articles from a template, so I don't have to add every component used on an article manually.

### Description
A new "Bulldog Magazine Article" template will be available, which contains the basic structure and blocks that all Bulldog Magazine blog articles share.

The scope of this issue is to create the template, every block contained in this template has a separate issue for its development.

### Acceptance Criteria 
- [x] Magazine Article template is available for authors to use and is added to the AEM Sidekick library, which contains the basic structure and blocks that all Volvo Magazine Articles share.
- [x] To set the magazine article title, authors can type standalone text and format it as an H2 if the Magazine Hero block has a title defined, or as an H1 if the Magazine Hero block doesn't have a title defined.
- [x] The Magazine Article template contains all of the following elements (in a general order of priority):
   - [x] aemsites/vg-macktrucks-com-old#766 (priority 1) Reflects the BE work needed. FE search will be implemented following https://github.com/hlxsites/vg-macktrucks-com-old/issues/913 otherwise the template can be created without search in the meantime.
 
   - [x]  aemsites/vg-macktrucks-com-old#746 (priority 2) Done
   - [x] aemsites/vg-macktrucks-com-old#749 (priority 2) Done
   - [x]  aemsites/vg-macktrucks-com-old#750 (priority 2) Done
   - [x] aemsites/vg-macktrucks-com#71 (priority 3) _Dependent on this ticket's completion. 
   - [x]  aemsites/vg-macktrucks-com-old#748 (priority 3)Done
   - [x] aemsites/vg-macktrucks-com-old#767 (priority 3) Done

- [x] To add the attribution and social block at the top of the page, a new variant of the v2 social block, named "attribution," will be created. The date and author information will be automatically pulled from the page's metadata.

### Notes 

- No subscribe block needs to be added as aemsites/vg-macktrucks-com#60  is still in backlog 

### Figma
[Magazine Article - Figma](https://www.figma.com/file/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2222%3A51379&mode=dev).

Desktop: 
![Image](https://github.com/user-attachments/assets/2c8e7400-d6b0-4850-b4a4-538d58579777)

Mobile: 
![Image](https://github.com/user-attachments/assets/26902d81-1e57-48ff-ae88-260ca20781a7)

**Comment by amglebihan** [comment]
The template can be found [here](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B81C6C7F5-2148-4BC2-831C-9629EAEDBA30%7D&file=v2-magazine-article-template.docx&action=default&mobileredirect=true), and the sub-navigation used within the template is defined [here](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BC2EBFDAB-C668-4199-A76A-5383BACFC21E%7D&file=v2-magazine-article-template-sub-navigation.docx&action=default&mobileredirect=true).

**Comment by bouchriy** [comment]
This issue has been migrated to Azure DevOps: https://dev.azure.com/volvo-digital-experience/DEX Platform/_workitems/edit/131966
